AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # Step 1: Create S3 Bucket for Raw Data
  RawDataS3Bucket:
    Type: 'AWS::S3::Bucket'
    #DeletionPolicy: Retain                        # this will retain bucket even stack Deleted
    Properties:
      BucketName: 'my-company-datalake-raw-data'
      #VersioningConfiguration:                    # Enables multiple versions of all objects in this bucket
      #  Status: Enabled
      #AccessControl: Private                      # By defualt it is private we can make it public

  # Step 2: Create S3 Bucket for Processed Data
  ProcessedDataS3Bucket:
    Type: 'AWS::S3::Bucket'
    #DeletionPolicy: Retain
    Properties:
      BucketName: 'my-company-datalake-processed-data'

  # Step 2: Create S3 Bucket for Curated Data
  ProcessedDataS3Bucket:
    Type: 'AWS::S3::Bucket'
    #DeletionPolicy: Retain
    Properties:
      BucketName: 'my-company-datalake-curated-data'